### ISSUE TITLE
Move into ember-polyfills org?

### ISSUE THREAD

**Issue by rwjblue** [ember-polyfills/ember-on-modifier#306]
I’ve been collecting the various polyfills that folks have made over in the ember-polyfills org. I’ve mostly been doing it as a way to increase bus factor, but it’s also super helpful to have a group of repo owners that are all conceptually familiar with the polyfill problem space. 

Think this repo is a good candidate for ember-polyfills?

**Comment by buschtoens** [comment]
Whoops! This must have slipped my attention. Sorry.

Sure, let's move it! 🚚
